version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    container_name: redis 
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-cache:/data
    restart: unless-stopped

  app:
    container_name: app
    build: .
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  pg-data:
  redis-cache:

    
